export type ID = string;

export type ViewMode = 'day' | 'week' | 'month' | 'agenda';

export interface Category {
  id: ID;
  name: string;
  color: string;
}

export interface Reminder {
  minutesBefore: number;
}

export interface RecurrenceRule {
  freq: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';
  interval?: number;
  byweekday?: number[];
  count?: number;
  until?: string;
}

export interface CalendarEvent {
  id: ID;
  title: string;
  description?: string;
  start: string;
  end: string;
  allDay?: boolean;
  categoryId?: ID;
  tags?: string[];
  recurrence?: RecurrenceRule;
  recurrenceExceptions?: string[];
  reminders?: Reminder[];
  location?: string;
  /**
   * If set, this event was generated by another module (a task with a
   * scheduledStart, a trip item, etc.). UI surfaces use this to:
   *   - mark virtual events as read-only on the calendar grid
   *   - offer a "Jump to source" affordance in the event modal
   *   - avoid duplicating data on save (the source is authoritative)
   *
   * For wellness items (`medication`, `meal`, `workout`) the id is composed
   * as `<entityId>::<occurrenceKey>` so each instance is uniquely addressable
   * (a 2x/day medication has two events per day with distinct occurrence keys).
   */
  sourceRef?: { type: 'task' | 'tripItem' | 'trip' | 'goal' | 'medication' | 'meal' | 'workout'; id: ID };
  createdAt: string;
  updatedAt: string;
}

export interface Goal {
  id: ID;
  title: string;
  description?: string;
  weekStart: string;
  done: boolean;
  /** Optional explicit target date — used by integrations to show goals on the calendar. */
  targetDate?: string; // yyyy-MM-dd
  /** Color used to render goal indicators in cross-module surfaces. */
  color?: string;
  createdAt: string;
}

export interface Habit {
  id: ID;
  name: string;
  emoji?: string;
  color: string;
  target: number;
  completions: Record<string, boolean>;
  /**
   * Optional goal this habit contributes to. When set, the goal card will roll
   * up the habit's weekly completion rate as a progress indicator.
   */
  goalId?: ID;
  createdAt: string;
}

export type BgTheme = 'aurora' | 'sunset' | 'ocean' | 'lavender' | 'forest' | 'candy' | 'mono';

export type FitnessGoal = 'lose' | 'maintain' | 'gain' | 'strength' | 'endurance' | 'general';
export type FitnessLevel = 'beginner' | 'intermediate' | 'advanced';
export type DietStyle =
  | 'omnivore'
  | 'vegetarian'
  | 'vegan'
  | 'pescatarian'
  | 'keto'
  | 'paleo'
  | 'mediterranean'
  | 'lowcarb'
  | 'other';
export type JournalingCadence = 'daily' | 'weekly' | 'occasional' | 'none';

/**
 * Lifestyle profile gathered during onboarding (and editable any time from
 * Personalize). Modules use these defaults to pre-fill new entries: Fitness
 * uses `preferredWorkoutTypes` + `workoutDaysPerWeek` when seeding a plan,
 * Meals uses `calorieTargetKcal` / `dietStyle` when logging meals, Sleep uses
 * `bedtime`/`wakeTime` for nightly reminders. Everything is optional so users
 * can skip the wellness step on first run.
 */
export interface WellnessProfile {
  // Fitness
  fitnessGoal?: FitnessGoal;
  fitnessLevel?: FitnessLevel;
  workoutDaysPerWeek?: number; // 0..7
  preferredWorkoutTypes?: WorkoutType[];
  equipment?: string[]; // free-form: 'gym', 'dumbbells', 'bands', 'kettlebell', 'bodyweight', 'cardio machine'
  heightCm?: number;
  weightKg?: number;

  // Diet
  dietStyle?: DietStyle;
  allergies?: string[]; // free-form: 'peanuts', 'gluten', 'dairy', ...
  dislikes?: string[];
  calorieTargetKcal?: number;
  proteinTargetG?: number;
  waterTargetMl?: number;

  // Sleep
  bedtime?: string; // HH:mm
  wakeTime?: string; // HH:mm
  sleepGoalHours?: number;

  // Mindfulness
  meditationMinutesPerDay?: number;
  journalingCadence?: JournalingCadence;
  gratitudePractice?: boolean;
}

export interface Settings {
  theme: 'light' | 'dark' | 'system';
  accent: string;
  bgTheme: BgTheme;
  weekStartsOn: 0 | 1;
  workDayStart: number;
  workDayEnd: number;
  slotMinutes: 15 | 30 | 60;
  notificationsEnabled: boolean;
  showWeekends: boolean;
  use24HourClock: boolean;
  currency: string; // ISO 4217 code, e.g. 'USD', 'EUR', 'GBP'

  // Personalization (set via onboarding, editable any time)
  displayName: string;
  avatarEmoji: string;
  focusAreas: string[]; // free-form tags (e.g. "Health", "Side project")
  visibleModules: ModuleId[]; // which modules show in the rail (empty = show all)
  wellness: WellnessProfile;
  onboardingCompleted: boolean;
}

// ────────────────────────────────────────────────────────────
// Module: Tasks (master list + kanban)
// ────────────────────────────────────────────────────────────
export type TaskStatus = 'todo' | 'doing' | 'done';
export type TaskPriority = 'low' | 'med' | 'high' | 'urgent';

export interface Task {
  id: ID;
  title: string;
  notes?: string;
  status: TaskStatus;
  priority?: TaskPriority;
  dueDate?: string; // ISO — when the task is due (date-only context)
  /**
   * When set, the task has a specific scheduled start time and renders as a
   * calendar block. Independent of `dueDate` so a task can be due Friday but
   * actually scheduled for Wednesday afternoon.
   */
  scheduledStart?: string; // ISO datetime
  /** Optional explicit duration (minutes). Defaults to 30 if scheduledStart set. */
  durationMin?: number;
  tags?: string[];
  projectId?: ID;
  categoryId?: ID;
  /**
   * When set, this task was generated from another entity (a trip, a habit
   * routine, etc.). Used by integration UI to show provenance and avoid
   * orphaning tasks when their source is deleted.
   */
  sourceRef?: { type: 'trip' | 'tripItem' | 'habit' | 'goal'; id: ID };
  /** When created from a calendar event, the event id (bidirectional link). */
  linkedEventId?: ID;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
}

export interface Project {
  id: ID;
  name: string;
  color: string;
  description?: string;
  archived?: boolean;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Module: Notes
// ────────────────────────────────────────────────────────────
export interface Note {
  id: ID;
  title: string;
  body: string;
  tags?: string[];
  pinned?: boolean;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Module: Journal
// ────────────────────────────────────────────────────────────
export type Mood = 1 | 2 | 3 | 4 | 5;

export interface JournalEntry {
  id: ID;
  date: string; // yyyy-MM-dd
  mood?: Mood;
  gratitude?: string;
  reflection?: string;
  highlights?: string;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Module: Finance (basic)
// ────────────────────────────────────────────────────────────
export type TxnKind = 'income' | 'expense';

export interface Transaction {
  id: ID;
  kind: TxnKind;
  amount: number;
  category: string; // free-form for now
  note?: string;
  date: string; // yyyy-MM-dd
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Module: Reading list
// ────────────────────────────────────────────────────────────
export type BookStatus = 'wishlist' | 'reading' | 'done';

export interface Book {
  id: ID;
  title: string;
  author?: string;
  status: BookStatus;
  progress?: number; // 0..100
  rating?: number; // 0..5
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Module: Bucket list / Vision
// ────────────────────────────────────────────────────────────
export interface BucketItem {
  id: ID;
  title: string;
  description?: string;
  imageUrl?: string;
  done?: boolean;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Module: Travel
// ────────────────────────────────────────────────────────────
export type TripStatus = 'idea' | 'planning' | 'booked' | 'active' | 'done';
export type TripItemType = 'flight' | 'transit' | 'lodging' | 'activity' | 'food' | 'note';

export interface Trip {
  id: ID;
  title: string;
  destination?: string;
  startDate?: string; // ISO or yyyy-MM-dd
  endDate?: string;
  status: TripStatus;
  color: string;
  notes?: string;
  imageUrl?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TripItem {
  id: ID;
  tripId: ID;
  type: TripItemType;
  title: string;
  date?: string; // yyyy-MM-dd
  time?: string; // HH:mm
  durationMin?: number;
  location?: string;
  notes?: string;
  confirmationCode?: string;
  cost?: number;
  done?: boolean;
  /** When the item has been pushed to the calendar, the linked event id. */
  linkedEventId?: ID;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Module: Wellness — Medications, Meals, Workouts
// ────────────────────────────────────────────────────────────

/**
 * The status of a single scheduled medication dose. Stored on `Medication.doses`
 * keyed by `${yyyy-MM-dd}T${HH:mm}` — each calendar occurrence is addressable.
 */
export type DoseStatus = 'taken' | 'skipped' | 'missed';

export interface Medication {
  id: ID;
  name: string;
  /** Free-form dosage label, e.g. "500mg", "2 pills", "10 units". */
  dosage?: string;
  /** Optional short instruction shown on the calendar tile. */
  instructions?: string;
  /** Hex color used for the calendar event + module accents. */
  color: string;
  /** Optional emoji shown on the dose tile. Defaults to "💊" downstream. */
  emoji?: string;
  /** Times of day to take the medication (HH:mm, 24h). */
  times: string[];
  /**
   * Days of the week the schedule applies to (0 = Sunday … 6 = Saturday).
   * Empty array or undefined = every day.
   */
  daysOfWeek?: number[];
  /** ISO date (yyyy-MM-dd) — first day the schedule is active. */
  startDate: string;
  /** ISO date (yyyy-MM-dd) — last day, exclusive of indefinite courses. */
  endDate?: string;
  /** Minutes before the dose time to fire a reminder. */
  reminderMinutesBefore?: number;
  /** Free-form notes (prescribing doctor, side-effects to watch, etc.). */
  notes?: string;
  /**
   * Dose log keyed by occurrence (`yyyy-MM-ddTHH:mm`). Absent key = pending /
   * not yet acted on.
   */
  doses: Record<string, DoseStatus>;
  /** Optional contact who should be notified if a dose is missed. */
  caregiverEmail?: string;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

export interface Meal {
  id: ID;
  title: string;
  type: MealType;
  /** yyyy-MM-dd. */
  date: string;
  /** HH:mm. */
  time?: string;
  /** Total kcal, if user wants to track. */
  calories?: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  notes?: string;
  /** True once the user marks the meal as eaten. */
  logged?: boolean;
  /** Optional photo URL (data URL or remote). Powers the photo-journal vision. */
  imageUrl?: string;
  recipeUrl?: string;
  createdAt: string;
  updatedAt: string;
}

export type WorkoutType = 'cardio' | 'strength' | 'flexibility' | 'sports' | 'other';
export type WorkoutIntensity = 'low' | 'medium' | 'high';

export interface WorkoutExercise {
  name: string;
  sets?: number;
  reps?: number;
  weight?: number;
  durationMin?: number;
  notes?: string;
}

export interface Workout {
  id: ID;
  name: string;
  type: WorkoutType;
  intensity?: WorkoutIntensity;
  /** yyyy-MM-dd. */
  date: string;
  /** HH:mm. */
  time?: string;
  durationMin?: number;
  exercises?: WorkoutExercise[];
  notes?: string;
  /** Marked done by the user. */
  completed?: boolean;
  caloriesBurned?: number;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// Modules (top-level navigation)
// ────────────────────────────────────────────────────────────
export type ModuleId =
  | 'today'
  | 'dashboard'
  | 'calendar'
  | 'tasks'
  | 'notes'
  | 'travel'
  | 'journal'
  | 'habits'
  | 'goals'
  | 'analytics'
  | 'finance'
  | 'medications'
  | 'meals'
  | 'fitness'
  | 'reading'
  | 'vision'
  | 'bucket'
  | 'archive'
  | 'ai';

export interface PlannerState {
  events: CalendarEvent[];
  categories: Category[];
  goals: Goal[];
  habits: Habit[];
  tasks: Task[];
  projects: Project[];
  notes: Note[];
  journal: JournalEntry[];
  transactions: Transaction[];
  books: Book[];
  bucket: BucketItem[];
  trips: Trip[];
  tripItems: TripItem[];
  medications: Medication[];
  meals: Meal[];
  workouts: Workout[];
  settings: Settings;
}

export interface EventInstance {
  event: CalendarEvent;
  start: Date;
  end: Date;
  occurrenceKey: string;
}

export interface Workspace {
  ownerId: string;
  ownerEmail?: string;
  role: 'owner' | 'editor' | 'viewer';
}

export interface PlannerInvite {
  token: string;
  ownerId: string;
  ownerEmail?: string;
  role: 'editor' | 'viewer';
  expiresAt: string;
  usedBy?: string;
  usedAt?: string;
  createdAt: string;
}

export interface PlannerMember {
  ownerId: string;
  memberId: string;
  ownerEmail?: string;
  memberEmail?: string;
  role: 'editor' | 'viewer';
  createdAt: string;
}

// ────────────────────────────────────────────────────────────
// Subscription / entitlements
// ────────────────────────────────────────────────────────────
export type SubscriptionTier = 'free' | 'plus' | 'pro';
export type SubscriptionStatus =
  | 'inactive'
  | 'trialing'
  | 'active'
  | 'past_due'
  | 'canceled';

export interface Subscription {
  userId: string;
  tier: SubscriptionTier;
  status: SubscriptionStatus;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  currentPeriodEnd?: string;
  aiMessagesUsed: number;
  aiPeriodStart: string;
  createdAt: string;
  updatedAt: string;
}
